---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: centos-5.8
    driver:
      box_url: https://dl.dropbox.com/u/17738575/CentOS-5.8-x86_64.box
      network:
        - ["private_network", {ip: "10.10.10.5"}]

suites:
  - name: default
    run_list:
      - recipe[tram::default]
