#!/bin/sh
#
# tram - this script starts and stops the tram daemon
#
# chkconfig:   2345 20 80
# description: Tram is a tram image daemon.
# processname: tram
# config:      /etc/tram.config
# config:      /etc/sysconfig/tram
# pidfile:     /var/run/tram.pid
 
# Source function library.
[ -f /etc/rc.d/init.d/functions ] && . /etc/rc.d/init.d/functions
 
# Source networking configuration.
[ -f /etc/sysconfig/network ] && . /etc/sysconfig/network
 
# Check that networking is up.
[ "$NETWORKING" = "no" ] && exit 0
 
tram="/home/tram/tram"
prog=$(basename $tram)
 
[ -f /etc/sysconfig/tram ] && . /etc/sysconfig/tram
 
start() {
    [ -x $tram ] || exit 5
    echo -n $"Starting $prog: "
    daemon $tram > /var/log/tram.log 2>&1 &
    retval=$?
    echo
    return $retval
}
 
stop() {
    echo -n $"Stopping $prog: "
    killproc $prog
    retval=$?
    echo
    return $retval
}
 
restart() {
    stop
    start
}
 
rh_status() {
    status $prog
}
 
rh_status_q() {
    rh_status >/dev/null 2>&1
}
 
case "$1" in
    start)
        rh_status_q && exit 0
        $1
        ;;
    stop)
        rh_status_q || exit 0
        $1
        ;;
    restart)
        $1
        ;;
    status)
        rh_status
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
        exit 2
esac
